VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "pppIWorker"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
Public Property Set Events(ByRef value As pppIWorkerEvents)
End Property
Sub Execute(Optional Args As pppTaskHTTP)
End Sub
Function CreateNew() As pppIWorker
End Function
